// This file is automatically generated by qtc from "loggedin_page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line loggedin_page.qtpl:1
package templates

//line loggedin_page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line loggedin_page.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line loggedin_page.qtpl:1
func StreamLoggedinPage(qw422016 *qt422016.Writer, data LoggedinData) {
	//line loggedin_page.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <!-- Latest compiled and minified CSS -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />

    <link href="https://lipis.github.io/bootstrap-social/bootstrap-social.css" rel="stylesheet" >
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-12" style="text-align:center">
          <h1>Beego OAuth 2.0 Demo</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4"></div>
              
        <div class="col-sm-4 social-buttons">
          <h3 class="text-center">User Account</h3>

          <p><strong>Name:</strong> `)
	//line loggedin_page.qtpl:30
	qw422016.E().S(data.User.Name.Formatted)
	//line loggedin_page.qtpl:30
	qw422016.N().S(`</p>
          <p><strong>Email:</strong> `)
	//line loggedin_page.qtpl:31
	qw422016.E().S(data.PrimaryEmail.Value)
	//line loggedin_page.qtpl:31
	qw422016.N().S(`</p>

          <button type="button" class="btn btn-default btn-md" style="width:100%">
            <a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Logout</a>
          </button>

          <p style="margin-top:1em;width:100%;text-align:center"><a href="https://`)
	//line loggedin_page.qtpl:37
	qw422016.E().S(DemoRepoURI)
	//line loggedin_page.qtpl:37
	qw422016.N().S(`">`)
	//line loggedin_page.qtpl:37
	qw422016.E().S(DemoRepoURI)
	//line loggedin_page.qtpl:37
	qw422016.N().S(`</a>
          
        </div>
      </div>
    </div>
  </body>
</html>
`)
//line loggedin_page.qtpl:44
}

//line loggedin_page.qtpl:44
func WriteLoggedinPage(qq422016 qtio422016.Writer, data LoggedinData) {
	//line loggedin_page.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line loggedin_page.qtpl:44
	StreamLoggedinPage(qw422016, data)
	//line loggedin_page.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line loggedin_page.qtpl:44
}

//line loggedin_page.qtpl:44
func LoggedinPage(data LoggedinData) string {
	//line loggedin_page.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line loggedin_page.qtpl:44
	WriteLoggedinPage(qb422016, data)
	//line loggedin_page.qtpl:44
	qs422016 := string(qb422016.B)
	//line loggedin_page.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line loggedin_page.qtpl:44
	return qs422016
//line loggedin_page.qtpl:44
}
