// This file is automatically generated by qtc from "login_page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:1
package templates

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:1
func StreamLoginPage(qw422016 *qt422016.Writer, data LoginData) {
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <!-- Latest compiled and minified CSS -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />

    <link href="https://lipis.github.io/bootstrap-social/bootstrap-social.css" rel="stylesheet" >

    <script>
// https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

var config = {
    google: {
        authUri: '`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:23
	qw422016.N().S(data.AuthURLGoogle())
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:23
	qw422016.N().S(`',
        redirectUri: '`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:24
	qw422016.N().S(data.OAuth2RedirectURI)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:24
	qw422016.N().S(`'
    },
    facebook: {
        authUri: '`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:27
	qw422016.N().S(data.AuthURLFacebook())
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:27
	qw422016.N().S(`',
        redirectUri: '`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:28
	qw422016.N().S(data.OAuth2RedirectURI)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:28
	qw422016.N().S(`'
    }
}

var OAuthCode = function(cfg) {
    this.config = config;
    this.loginPopup  = function(service) {
        var cfg = this.config;
        this.loginPopupUri(cfg[service]['authUri'], cfg[service]['redirectUri']);
    }
    this.loginPopupUri = function(authUri, redirectUri) {
        var win        = window.open(authUri, 'windowname1', 'width=800, height=600'); 
        var pollOAuth  = window.setInterval(function() { 
            try {
                console.log("DOCUMENT_URI: " + win.document.URL);
                console.log("REDIRECT_URI: " + redirectUri);
                if (win.document.URL.indexOf(redirectUri) != -1) {
                    window.clearInterval(pollOAuth);
                    win.close();
                    location.reload();
                }
            } catch(e) {
                console.log(e)
            }
        }, 100);
    }
}
var oauth = new OAuthCode(config);
    </script>

  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-12" style="text-align:center">
          <h1>Beego OAuth 2.0 Demo</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4"></div>
              
        <div class="col-sm-4 social-buttons">
          <h3 class="text-center">Login</h3>

          <a class="btn btn-block btn-social btn-google" onclick="oauth.loginPopup('google'); return false;">
            <span class="fa fa-google"></span> Sign in with Google
          </a>

          <a class="btn btn-block btn-social btn-facebook" onclick="oauth.loginPopup('facebook'); return false;">
            <span class="fa fa-facebook"></span> Sign in with Facebook
          </a>

          <p style="margin-top:1em;width:100%;text-align:center"><a href="https://`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:82
	qw422016.E().S(DemoRepoURI)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:82
	qw422016.N().S(`">`)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:82
	qw422016.E().S(DemoRepoURI)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:82
	qw422016.N().S(`</a>

        </div>
      </div>
    </div>
  </body>
</html>
`)
//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
}

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
func WriteLoginPage(qq422016 qtio422016.Writer, data LoginData) {
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	StreamLoginPage(qw422016, data)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
}

//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
func LoginPage(data LoginData) string {
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	WriteLoginPage(qb422016, data)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	qs422016 := string(qb422016.B)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
	//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
	return qs422016
//line grokify/beego-oauth2-demo/templates/login_page.qtpl:89
}
