// Code generated by qtc from "oauth2callback.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line oauth2callback.qtpl:1
package templates

//line oauth2callback.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line oauth2callback.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line oauth2callback.qtpl:1
func StreamOAuth2CallbackPage(qw422016 *qt422016.Writer, data LoginData) {
//line oauth2callback.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <script>

function receiveMessage(event) {
  console.log("I_GOT_EVENT ["+event.origin+ "]["+event.data+"]");
  if (event.origin !== '`)
//line oauth2callback.qtpl:11
	qw422016.N().S(data.BaseUri)
//line oauth2callback.qtpl:11
	qw422016.N().S(`') {
    return;
  }
  event.source.postMessage('oauth2redirectisfinished', event.origin);
  window.close();
}
window.addEventListener("message", receiveMessage, false);

    </script>
  </head>
  <body>
  </body>
</html>
`)
//line oauth2callback.qtpl:24
}

//line oauth2callback.qtpl:24
func WriteOAuth2CallbackPage(qq422016 qtio422016.Writer, data LoginData) {
//line oauth2callback.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line oauth2callback.qtpl:24
	StreamOAuth2CallbackPage(qw422016, data)
//line oauth2callback.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line oauth2callback.qtpl:24
}

//line oauth2callback.qtpl:24
func OAuth2CallbackPage(data LoginData) string {
//line oauth2callback.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line oauth2callback.qtpl:24
	WriteOAuth2CallbackPage(qb422016, data)
//line oauth2callback.qtpl:24
	qs422016 := string(qb422016.B)
//line oauth2callback.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line oauth2callback.qtpl:24
	return qs422016
//line oauth2callback.qtpl:24
}
